### PR TITLE
Adding rpm package build

### PR DESCRIPTION
**Pull request by jaroslawp**
Since I'm using an rpm distro: CentOS 7 .. this PR proposes to add rpm building to gstm.

### CODE REVIEW

**Comment by dallenwilson** [comment]
I've been keeping all the packaging information out of the git repository. Is there anything similar to Launchpad's [Personal Package Archives](https://help.launchpad.net/Packaging/PPA) available for rpm-based distributions?

**Comment by jaroslawp** [comment]
There is  [Fedora COPR](https://docs.pagure.org/copr.copr/) which can build for multiple rpm distirbutions (Fedora/Centos/Mageia/OpenSUSE) .. but in standard setup it would still require the cloned repository to contain an rpm spec file (or a Makefile target specific to copr).
COPR has the possibility to execute a custom script for builds too: but then that one needs to be maintained separately from the source repository of course in the COPR system itself and using it that way would not allow to benefit from github -> copr integration via webhooks for example it  seems .. (I'm not really expert on COPR .. just read some docs...)

**Comment by dallenwilson** [comment]
I did some searching myself, it looks like [Open Build Service](https://openbuildservice.org/) would also do the job.

I'll dig in to it and see if I can set it up. If rpm packaging stuff is here, then I may move the debian/deb stuff in-repo as well. It would make my life a bit easier with launchpad.

One thing: Please add `Requires: util-linux` to gstm.spec.in. The gstm.desktop file launches gstm using setsid from that package, to ensure the SSH_ASKPASS envvar is properly used by ssh. The readme has not been updated with that yet.

**Comment by jaroslawp** [comment]
Yes, OBS is also a good alternative (I'm more RHEL biased hence COPR :-))  !
I believe that a self-contained repo including everything , so also packaging is better, but thats only my opinion of course ;-)
The require for util-linux has just been added.

**Comment by dallenwilson** [comment]
Well, you talked me in to it.

**Pull request merged**
